var movies = [
	{
		'id' : 1,
		'name' : 'Filme do Centeno',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},
	{
		'id' : 1,
		'name' : 'Teste de filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},	
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},	
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},	
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},	
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},	
	{
		'id' : 1,
		'name' : 'Nome completo do filme',
		'country' : '',
		'year' : 2012,
		'date' : '2014-01-01',
		'place' : 'Cinemark',
		'fellows' : '',
		'gender' : '',
		'rate' : 10,
		'comments' : '',
		'image' : '1.jpg'
	},	

];
